development:
  tmpDir: tmp
  username: developer
  password: password
  database: quartermaster-dev
  adapter: postgres

test:
  tmpDir: tmp
  username: developer
  password: password
  database: quartermaster-test
  adapter: postgres

production:
  tmpDir: tmp
  username:
  password:
